CC = g++

CFLAGS = -Wall -Werror -c -g
INCLUDES = -I./include -I/usr/local/include -L/usr/local/lib
LDFLAGS = -lwiringPi -lboost_thread -lboost_system -g

SOURCES = $(wildcard include/*.cpp)
EXECUTABLES = bin/lawnmower bin/waypoints2 bin/waypoints bin/saveWaypoints

HEADERS = $(SOURCES: .cpp = .h)
OBJECTS = $(SOURCES: .cpp = .o)


all: $(EXECUTABLES)


bin/lawnmower : obj/lawnmower.o $(OBJECTS)
	$(CC) $(LDFLAGS) $(OBJECTS) obj/lawnmower.o -o bin/lawnmower

bin/waypoints2 : obj/waypoints2.o $(OBJECTS)
	$(CC) $(LDFLAGS) $(OBJECTS) obj/waypoints2.o -o bin/waypoints2

bin/waypoints : obj/waypoints.o $(OBJECTS)
	$(CC) $(LDFLAGS) $(OBJECTS) obj/waypoints.o -o bin/waypoints

bin/saveWaypoints : obj/saveWaypoints.o $(OBJECTS)
	$(CC) $(LDFLAGS) $(OBJECTS) obj/saveWaypoints.o -o bin/saveWaypoints

obj/lawnmower.o : $(HEADERS) $(SOURCES)
	$(CC) $(CFLAGS) $(INCLUDES) src/lawnmower.cpp -o obj/lawnmower.o

obj/waypoints2.o : $(HEADERS) $(SOURCES)
	$(CC) $(CFLAGS) $(INCLUDES) src/waypoints2.cpp -o obj/waypoints2.o

obj/waypoints.o : $(HEADERS) $(SOURCES)
	$(CC) $(CFLAGS) $(INCLUDES) src/waypoints.cpp -o obj/waypoints.o

obj/saveWaypoints.o : include/gps_qstarz.h include/gps_qstarz.cpp
	$(CC) $(CFLAGS) $(INCLUDES) src/saveWaypoints.cpp -o obj/saveWaypoints.o

obj/flightBoard.o : include/flightBoard.h include/flightBoard.cpp include/gpio.h include/gpio.cpp
	$(CC) $(CFLAGS) $(INCLUDES) include/flightBoard.cpp -o obj/flightBoard.o

obj/gps_qstarz.o : include/gps_qstarz.h include/gps_qstarz.cpp
	$(CC) $(CFLAGS) $(INCLUDES) include/gps_qstarz.cpp -o obj/gps_qstarz.o

obj/gpio.o : include/gpio.h include/gpio.cpp 
	$(CC) $(CFLAGS) $(INCLUDES) include/gpio.cpp -o obj/gpio.o

obj/logger.o : include/logger.h include/logger.cpp
	$(CC) $(CFLAGS) $(INCLUDES) include/logger.cpp -o obj/logger.o

clean:
	rm -f obj/*.o bin/* 
