/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef picopter_CONSTANTS_H
#define picopter_CONSTANTS_H

#include "picopter_types.h"

namespace picopter {

class picopterConstants {
 public:
  picopterConstants();

};

extern const picopterConstants g_picopter_constants;

} // namespace

#endif
