/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "picopter_constants.h"

namespace picopter {

const picopterConstants g_picopter_constants;

picopterConstants::picopterConstants() {
}

} // namespace

